---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "vaultwarden.fullname" . }}
  labels:
    {{- include "vaultwarden.labels" . | nindent 4 }}
stringData:
	{{- with .Values.vaultwarden.config }}
  {{- if not (hasKey . "DATA_FOLDER") }}
  DATA_FOLDER: /var/lib/vaultwarden
  {{- end }}
  {{- . | toYaml | nindent 2 }}
  {{- end }}
