from docker.io/library/python:3-alpine as builder

	arg VERSION

	run apk --no-cache add \
		libxml2-dev \
		libxslt-dev \
		gcc \
		musl-dev \
		g++ \
		bison \
		flex

	run pip3 install \
		--root-user-action="ignore" \
		--prefix="/install" \
		fava=="${VERSION}"

from docker.io/library/python:3-alpine

	copy --from=builder /install /usr/local

	expose 8080/tcp

	volume /data
	volume /plugins

	env LC_ALL "C.UTF-8"
	env LANG "C.UTF-8"
	env PYTHONPATH "${PYTHONPATH}:/plugins"
	env FAVA_HOST "0.0.0.0"
	env FAVA_PORT "8080"

	cmd [ "fava", "/data/ledger.beancount" ]
