version: '3'

services:
  fava:
    container_name: 'fava'
    image: 'ghcr.io/lukasdietrich/dockerized-fava:latest'
    restart: 'unless-stopped'
    logging:
      driver: 'journald'

    ports:
      - '5000:5000'

    volumes:
      - './data:/data'
