version: '3'

services:
  meshcentral:
    container_name: 'meshcentral'
    image: 'ghcr.io/lukasdietrich/dockerized-meshcentral'
    restart: 'unless-stopped'
    logging:
      driver: 'journald'

    volumes:
      - './volumes/meshcentral-data:/app/meshcentral-data'
      - './volumes/meshcentral-files:/app/meshcentral-files'
