apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "paperless-ngx.fullname" . }}
  labels:
    {{- include "paperless-ngx.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "paperless-ngx.selectorLabels" . | nindent 6 }}
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        checksum/secret: {{ include (print .Template.BasePath "/secrets.yaml") . | sha256sum }}
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "paperless-ngx.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "paperless-ngx.serviceAccountName" . }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          {{- with .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
          {{- with .Values.persistence }}
          {{- if .data.enabled }}
            - name: paperless-data
              mountPath: /usr/src/paperless/data
          {{- end }}
          {{- if .media.enabled }}
            - name: paperless-media
              mountPath: /usr/src/paperless/media
          {{- end }}
          {{- if .consume.enabled }}
            - name: paperless-consume
              mountPath: /usr/src/paperless/consume
          {{- end }}
          {{- end }}
          {{- with .Values.volumeMounts }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
          envFrom:
            - secretRef:
                name: {{ include "paperless-ngx.fullname" . }}
      volumes:
      {{- with .Values.persistence }}
      {{- with .data }}
      {{- if .enabled }}
        - name: paperless-data
          persistentVolumeClaim:
            {{- if .existingClaimName }}
            claimName: {{ .existingClaimName | quote }}
            {{- else }}
            claimName: {{ include "paperless-ngx.fullname" $ }}-data
            {{- end }}
      {{- end }}
      {{- end }}
      {{- with .media }}
      {{- if .enabled }}
        - name: paperless-media
          persistentVolumeClaim:
            {{- if .existingClaimName }}
            claimName: {{ .existingClaimName | quote }}
            {{- else }}
            claimName: {{ include "paperless-ngx.fullname" $ }}-media
            {{- end }}
      {{- end }}
      {{- end }}
      {{- with .consume }}
      {{- if .enabled }}
        - name: paperless-consume
          persistentVolumeClaim:
            {{- if .existingClaimName }}
            claimName: {{ .existingClaimName | quote }}
            {{- else }}
            claimName: {{ include "paperless-ngx.fullname" $ }}-consume
            {{- end }}
      {{- end }}
      {{- end }}
      {{- end }}
      {{- with .Values.volumes }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
