---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "paperless-ngx.fullname" . }}
  labels:
    {{- include "paperless-ngx.labels" . | nindent 4 }}
{{- with .Values.paperless }}
stringData:
  {{-  $timezone := .timezone | default "Europe/Berlin" | quote }}
  TZ: {{ $timezone }}
  PAPERLESS_TIME_ZONE: {{ $timezone }}
  {{- with .database }}
  PAPERLESS_DBENGINE: {{ .engine | quote }}
  PAPERLESS_DBHOST: {{ .host | quote }}
  PAPERLESS_DBPORT: {{ .port | quote }}
  {{- with .credentials }}
  PAPERLESS_DBUSER: {{ .username | quote }}
  PAPERLESS_DBPASS: {{ .password | quote }}
  {{- end }}
  {{- end }}
  {{- with .redis }}
  PAPERLESS_REDIS: {{ .url | quote }}
  {{- end }}
  PAPERLESS_SECRET_KEY: {{ (randAscii 64) | quote }}
  {{- with $.Values.ingress }}
  {{- if .enabled }}
  {{- $scheme := .tls | empty | ternary "http" "https" }}
  {{- $host := .hosts | first  }}
  PAPERLESS_URL: {{ urlJoin (dict "scheme" $scheme "host" (get $host "host")) }}
  {{- end }}
  {{- end }}
  {{- with .login }}
  {{- with .regular }}
  PAPERLESS_DISABLE_REGULAR_LOGIN: {{ .enabled | quote }}
  {{- end }}
  {{- with .oauth2 }}
  {{- if .enabled }}
  PAPERLESS_REDIRECT_LOGIN_TO_SSO: {{ .redirect | quote }}
  PAPERLESS_APPS: allauth.socialaccount.providers.openid_connect
  PAPERLESS_SOCIAL_AUTO_SIGNUP: "true"
  PAPERLESS_SOCIALACCOUNT_PROVIDERS: >-
    {
      "openid_connect": {
        "APPS": [
          {
            {{- with .provider }}
            "provider_id": {{ .id | quote }},
            "name": {{ .name | quote }},
            {{- end }}
            {{- with .client }}
            "client_id": {{ .id | quote }},
            "secret": {{ .secret | quote }},
            {{- end }}
            "settings": {
              {{- $wellKnown := printf "%s%s" .issuer.url "/.well-known/openid-configuration" }}
              "server_url": {{ $wellKnown | quote }}
            }
          }
        ]
      }
    }
  {{- end }}
  {{- end }}
  {{- end }}
  {{- with .ocr }}
  PAPERLESS_OCR_LANGUAGE: {{ .language | quote }}
  PAPERLESS_OCR_MODE: {{ .mode | quote }}
  PAPERLESS_OCR_CLEAN: {{ .clean | quote }}
  {{- end }}
  {{- with .cron }}
  PAPERLESS_EMAIL_TASK_CRON: {{ .email | quote }}
  PAPERLESS_TRAIN_TASK_CRON: {{ .train | quote }}
  PAPERLESS_INDEX_TASK_CRON: {{ .index | quote }}
  PAPERLESS_SANITY_TASK_CRON: {{ .sanity | quote }}
  {{- end }}
  {{- with .consumer }}
  PAPERLESS_CONSUMER_DISABLE: {{ not .enabled | quote }}
  {{- end }}
{{- end }}
