name: MeshCentral

on:
  workflow_dispatch:
  push:
    branches:
      - 'master'
    paths:
      - 'meshcentral/**'

jobs:
  docker:
    name: Publish MeshCentral
    runs-on: ubuntu-latest

    steps:
      - name: Check out Dockerfile
        uses: actions/checkout@v2
 
      - name: Login to GitHub Packages Docker Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ github.token }}

      - name: Build and Push image
        uses: docker/build-push-action@v2
        with:
          context: ./meshcentral
          push: true
          tags: ghcr.io/lukasdietrich/dockerized-meshcentral:latest
          labels:
            | org.opencontainers.image.title=MeshCentral
            | org.opencontainers.image.url=https://github.com/lukasdietrich/dockerized
            | org.opencontainers.image.source=https://github.com/lukasdietrich/dockerized
            | org.opencontainers.image.licenses=Unlicense
